install_yum_common: &install_yum_common
  image: ${IMAGE}
  commands:
    - echo "[metwork]" >/etc/yum.repos.d/metwork.repo
    - echo "name=metwork" >>/etc/yum.repos.d/metwork.repo
    - echo "baseurl=http://metwork-framework.org/pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/portable/" >>/etc/yum.repos.d/metwork.repo
    - echo "gpgcheck=0" >>/etc/yum.repos.d/metwork.repo
    - echo "enabled=1" >>/etc/yum.repos.d/metwork.repo
    - echo "metadata_expire=0" >>/etc/yum.repos.d/metwork.repo
    - yum -y install metwork-mfext-full git
    - git clone https://github.com/metwork-framework/mfext src
    - cd src && git checkout ${DRONE_BRANCH}
    - cd integration_tests && /opt/metwork-mfext/bin/mfext_wrapper ./run_integration_tests.sh

install_urpmi_common: &install_urpmi_common
  image: ${IMAGE}
  commands:
    - urpmi.addmedia metwork http://metwork-framework.org/pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/portable/
    - yes |urpmi git wget
    - yes |urpmi metwork-mfext-full
    - git clone https://github.com/metwork-framework/mfext src
    - cd src && git checkout ${DRONE_BRANCH}
    - cd integration_tests && /opt/metwork-mfext/bin/mfext_wrapper ./run_integration_tests.sh

pipeline:
  install_centos6:
    <<: *install_yum_common
    when:
      matrix:
        IMAGE: centos:centos6
  install_centos7:
    <<: *install_yum_common
    when:
      matrix:
        IMAGE: centos:centos7
  install_centos8:
    <<: *install_yum_common
    when:
      matrix:
        IMAGE: centos:centos8
  install_fedora29:
    <<: *install_yum_common
    when:
      matrix:
        IMAGE: fedora:29
  install_fedora30:
    <<: *install_yum_common
    when:
      matrix:
        IMAGE: fedora:30
  install_mageia6:
    <<: *install_urpmi_common
    when:
      matrix:
        IMAGE: mageia:6
  install_mageia7:
    <<: *install_urpmi_common
    when:
      matrix:
        IMAGE: mageia:7

matrix:
  IMAGE:
    - centos:centos6
    - centos:centos7
    - roboxes/centos8
    - fedora:29
    - fedora:30
    - opensuse/leap:15.0
    - opensuse/leap:15.1
    - opensuse/leap:42.3
    - mageia:6
    - mageia:7
